const projectsList = [{
    name: 'Oscar 2017',
    img: 'assets/img/oscar.png',
    technologies: ['HMTL5', 'CSS3'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj001',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj001/',
  },
  {
    name: 'News Card',
    img: 'assets/img/news-card.png',
    technologies: ['HTML5', 'CSS'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj002',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj002/',
  },
  {
    name: 'Login Page',
    img: 'assets/img/login-page.png',
    technologies: ['HTML5', 'CSS3'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj003',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj003/',
  },
  {
    name: 'Projects List',
    img: 'assets/img/projects-list.png',
    technologies: ['HTML5', 'CSS3'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj004',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj004/',
  },
  {
    name: 'Report Table',
    img: 'assets/img/report-table.png',
    technologies: ['HTML5', 'CSS3'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj005',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj005/',
  },
  {
    name: 'Responsive Feed',
    img: 'assets/img/responsive-feed.png',
    technologies: ['HTML5', 'CSS3'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj006',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj006/',
  },
  {
    name: 'Responsive Landing Page',
    img: 'assets/img/responsive-landing-page.png',
    technologies: ['HTML5', 'CSS3'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj007',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj007/',
  },
  {
    name: 'Admin Dashboard',
    img: 'assets/img/admin-dashboard.png',
    technologies: ['HTML5', 'CSS3'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj008',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj008/',
  },
  {
    name: 'Checkout Page',
    img: 'assets/img/checkout-page.png',
    technologies: ['HTML5', 'CSS3', 'Google Fonts'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj009',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj009/',
  },
  {
    name: 'Curriculum',
    img: 'assets/img/curriculum.png',
    technologies: ['HTML5', 'CSS3', 'Bulma', 'Font Awesome', 'Google Fonts'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj010',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj010/',
  },
  {
    name: 'Calculadora de IMC',
    img: 'assets/img/calculadora-imc.png',
    technologies: ['HTML5', 'CSS3', 'Javascript', 'Google Fonts'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj011',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj011/',
  },
  {
    name: 'Conversor Dólar/Real',
    img: 'assets/img/conversor-dolar-real.png',
    technologies: ['HTML5', 'CSS3', 'Javascript', 'Google Fonts'],
    linkCode: 'https://github.com/DouglasRenato/pm-projetos/tree/master/pm-proj012',
    linkLive: 'https://douglasrenato.github.io/pm-projetos/pm-proj012/',
  },
  {
    name: 'Busca Endereço via CEP',
    img: 'assets/img/busca-endereco-via-cep.png',
    technologies: ['HTML5', 'CSS3', 'Javascript', 'Google Fonts', 'Font Awesome'],
    linkCode: 'https://github.com/DouglasRenato/busca-endereco-via-cep',
    linkLive: 'https://douglasrenato.github.io/busca-endereco-via-cep/',
  },
  {
    name: 'Horário e Data Ao Vivo',
    img: 'assets/img/horario-e-data-ao-vivo.png',
    technologies: ['HTML5', 'CSS3', 'Javascript', 'Google Fonts', 'Font Awesome'],
    linkCode: 'https://github.com/DouglasRenato/horario-e-data-ao-vivo',
    linkLive: 'https://douglasrenato.github.io/horario-e-data-ao-vivo/',
  },
  {
    name: 'Landing Page Air BnB',
    img: 'assets/img/landing-page-air-bnb.png',
    technologies: ['HTML5', 'CSS3', 'Javascript', 'Google Fonts', 'Font Awesome'],
    linkCode: 'https://github.com/DouglasRenato/landing-page-airbnb',
    linkLive: 'https://douglasrenato.github.io/landing-page-airbnb/',
  },
  {
    name: 'Contagem Regressiva para o Natal ',
    img: 'assets/img/contagem-para-o-natal.png',
    technologies: ['HTML5', 'CSS3', 'Javascript', 'Google Fonts', 'Font Awesome', 'AOS - Animate On Scroll'],
    linkCode: 'https://github.com/DouglasRenato/contagem-regressiva-para-o-natal',
    linkLive: 'https://douglasrenato.github.io/contagem-regressiva-para-o-natal/',
  },
  {
    name: 'GitHub Info',
    img: 'assets/img/github-info.png',
    technologies: ['HTML5', 'CSS3', 'Javascript', 'ES5', 'Boostrap 4', 'Font Awesome', 'NodeJS', 'ReactJS', 'Axios'],
    linkCode: 'https://github.com/DouglasRenato/github-info-reactjs',
    linkLive: 'https://douglasrenato.github.io/github-info-reactjs/',
  },
  {
    name: 'GitHub Info (ES6)',
    img: 'assets/img/github-info-es6.png',
    technologies: ['HTML5', 'CSS3', 'Javascript', 'ES6', 'reactstrap', 'Font Awesome', 'NodeJS', 'ReactJS', 'Axios'],
    linkCode: 'https://github.com/DouglasRenato/github-info-reactjs-es6',
    linkLive: 'https://douglasrenato.github.io/github-info-reactjs-es6/',
  },
];